name: Detele Files
on: 
  push:
  schedule:
      - cron: "30 0 * * *"
  
env:
  ## Sets environment variable
  DIRECTORY_TO_DELETE: deleter 
  BRANCH: main
  MESSAGE: Testing
  NAME : FernanApps
  EMAIL : fernan.apps@github.com

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Delete files of directory
        run: |
          rm -r DIRECTORY_TO_DELETE
          ls -la
          echo "---------- VARIABLES ---------------"
          echo "DIRECTORY_TO_DELETE - ${{env.API_KEY}}"
          echo "BRANCH - ${{env.BRANCH}}"
          echo "MESSAGE - ${{env.MESSAGE}}"
          echo "NAME - ${{env.NAME}}"
          echo "EMAIL - ${{env.EMAIL}}"
          echo "---------- VARIABLES ---------------"


      - name: Pushing to main branch
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: BRANCH
          message: MESSAGE
          author_name: NAME
          author_email: EMAIL
          force: true
